datasources:
  - type: airtable
    base: app1234567890abcdef
    view: View 1
    status_field: Status
    incomplete_value: Not Done
    complete_value: Done
    project: Project 1
    
  - type: markdown_file
    file: ~/Documents/tasks.md
    project: Project 2

  - type: markdown_dir
    dir: ~/Documents/Projects
    recursive: false